name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gha/*
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build
        run: deno task build
      - name: Build Perms
        run: deno task build-perms
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/
      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/dlsl_preproc.exe, bin/dlsl_preproc, bin/dlsl_preproc_perms.exe, bin/dlsl_preproc_perms
