name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gha/*
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Version Number
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: version_number
        run: |
          TAG=${{ github.ref_name }}
          echo "${TAG#v}"
          echo "version_number=${TAG#v}" >> $GITHUB_OUTPUT
      - name: Version
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          sed -i -e "s/\"version\": \"dev\"/\"version\": \"${{ steps.version_number.outputs.version_number }}\"/g" src/meta.json
      - name: Build
        run: deno task build
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/
      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/*
